- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Update packages
    apt:
      upgrade: yes
      update_cache: yes

  - name: Install packages
    apt:
      name:
        - htop
        - mc
        - tmux