- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Update cache
    apt:
      update_cache: yes

  - name: Update packages
    apt:
      name: "*"
      state: latest

  - name: Autoremove
    apt:
      autoremove: yes